# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cpf < Formula
  desc "A CLI tool to validate, format and generate Brazilian CPF numbers"
  homepage "https://github.com/diegopeixoto/go-cpf-cli"
  version "1.8.0"
  license "MIT"

  depends_on "go" => :build
  depends_on :macos

  on_intel do
    url "https://github.com/diegopeixoto/go-cpf-cli/releases/download/v1.8.0/go-cpf-cli_Darwin_x86_64.zip"
    sha256 "bea6f169d6f65448120dfecd38c17a3d700210a6980ec3472f82d9abf1070d74"

    def install
      bin.install "cpf"
    end
  end
  on_arm do
    url "https://github.com/diegopeixoto/go-cpf-cli/releases/download/v1.8.0/go-cpf-cli_Darwin_arm64.zip"
    sha256 "ee092decaf466ff14584c36ef55722000b02997eb6c2af1e4d028717f8e8dcee"

    def install
      bin.install "cpf"
    end
  end

  def caveats
    <<~EOS
      To use cpf, you can run commands like:
        cpf validate 123.456.789-09
        cpf generate --count=5
        cpf format 12345678909
    EOS
  end

  test do
    system "#{bin}/cpf", "--version"
    output = shell_output("#{bin}/cpf generate --count=1")
    assert_match(/\d{3}\.\d{3}\.\d{3}-\d{2}/, output)
  end
end
